#!/usr/bin/env bash
# =============================================================================
# CompliBoss — generate production env files for the docker-compose demo deploy.
#
#   bash deploy/setup-env.sh compliboss.com
#
# Writes (relative to repo root):
#   .env               (docker compose interpolation: build args, DB password)
#   apps/api/.env      (NestJS API — auth + business logic)
#   apps/app/.env      (dashboard)
#   apps/portal/.env   (portal — minimal; only needed if you run the portal svc)
#
# Secrets are generated once and SHARED where they must match (api <-> app).
# Re-running regenerates everything (new secrets) — only run once per install
# unless you intend to rotate.
# =============================================================================
set -euo pipefail

DOMAIN="${1:-compliboss.com}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

APP_URL="https://app.${DOMAIN}"
API_URL="https://api.${DOMAIN}"
PORTAL_URL="https://portal.${DOMAIN}"

gen() { openssl rand -base64 32 | tr -d '\n'; }

# Shared secrets — MUST be identical across api and app.
AUTH_SECRET="$(gen)"
SECRET_KEY="$(gen)"
INTERNAL_API_TOKEN="$(gen)"
REVALIDATION_SECRET="$(gen)"
SERVICE_TOKEN_PORTAL="$(gen)"
SERVICE_TOKEN_TRIGGER="$(gen)"
POSTGRES_PASSWORD="$(openssl rand -hex 16)"

DB_URL="postgresql://compliboss:${POSTGRES_PASSWORD}@postgres:5432/compliboss"

echo "Generating env for domain: ${DOMAIN}"

# ---- root .env (docker compose reads this for build args + interpolation) ----
cat > "${ROOT}/.env" <<EOF
# Auto-generated by deploy/setup-env.sh — do NOT commit.
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Build-time public URLs (used as docker-compose build args)
BETTER_AUTH_URL=${APP_URL}
BETTER_AUTH_URL_PORTAL=${PORTAL_URL}
NEXT_PUBLIC_API_URL=${API_URL}
NEXT_PUBLIC_PORTAL_URL=${PORTAL_URL}

# MinIO (unused when STORAGE_DRIVER=local, but compose references them)
MINIO_ROOT_USER=compliboss
MINIO_ROOT_PASSWORD=$(openssl rand -hex 12)
EOF

# ---- apps/api/.env ----
cat > "${ROOT}/apps/api/.env" <<EOF
# Auto-generated by deploy/setup-env.sh — do NOT commit.
NODE_ENV=production
PORT=3333
BASE_URL=${API_URL}
BETTER_AUTH_URL=${APP_URL}
NEXT_PUBLIC_APP_URL=${APP_URL}
NEXT_PUBLIC_API_URL=${API_URL}

DATABASE_URL=${DB_URL}

AUTH_SECRET=${AUTH_SECRET}
BETTER_AUTH_SECRET=${AUTH_SECRET}
SECRET_KEY=${SECRET_KEY}
INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN}
SERVICE_TOKEN_PORTAL=${SERVICE_TOKEN_PORTAL}
SERVICE_TOKEN_TRIGGER=${SERVICE_TOKEN_TRIGGER}

# Cross-subdomain session cookies
COOKIE_DOMAIN=.${DOMAIN}
PUBLIC_ROOT_DOMAIN=${DOMAIN}
AUTH_TRUSTED_ORIGINS=${APP_URL},${PORTAL_URL},${API_URL}

# Local file storage (mounted persistent volume in docker-compose.prod.yml)
STORAGE_DRIVER=local
LOCAL_STORAGE_DIR=/var/lib/compliboss/uploads

# Feature dummies (inert without real keys) — demo runs without these:
MACED_API_KEY=mc_dev_dummy_api_key
# RESEND_API_KEY=            # leave unset for demo; OTP/magic-link prints to API logs
# OPENAI_API_KEY=           # set to enable AI policy/vendor/risk generation
EOF

# ---- apps/app/.env ----
cat > "${ROOT}/apps/app/.env" <<EOF
# Auto-generated by deploy/setup-env.sh — do NOT commit.
NODE_ENV=production
DATABASE_URL=${DB_URL}

AUTH_SECRET=${AUTH_SECRET}
BETTER_AUTH_SECRET=${AUTH_SECRET}
SECRET_KEY=${SECRET_KEY}
INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN}
REVALIDATION_SECRET=${REVALIDATION_SECRET}

BETTER_AUTH_URL=${APP_URL}
NEXT_PUBLIC_BETTER_AUTH_URL=${APP_URL}
NEXT_PUBLIC_API_URL=${API_URL}
NEXT_PUBLIC_PORTAL_URL=${PORTAL_URL}
NEXT_OUTPUT_STANDALONE=true
EOF

# ---- apps/portal/.env (minimal; only used if the portal service is run) ----
cat > "${ROOT}/apps/portal/.env" <<EOF
# Auto-generated by deploy/setup-env.sh — do NOT commit.
NODE_ENV=production
DATABASE_URL=${DB_URL}
AUTH_SECRET=${AUTH_SECRET}
BETTER_AUTH_SECRET=${AUTH_SECRET}
SECRET_KEY=${SECRET_KEY}
INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN}
SERVICE_TOKEN_PORTAL=${SERVICE_TOKEN_PORTAL}
BETTER_AUTH_URL=${PORTAL_URL}
NEXT_PUBLIC_BETTER_AUTH_URL=${PORTAL_URL}
NEXT_PUBLIC_API_URL=${API_URL}
EOF

echo "Wrote: .env, apps/api/.env, apps/app/.env, apps/portal/.env"
echo "POSTGRES_PASSWORD and all secrets generated. Keep the .env files safe."
